### ISSUE TITLE
Hi,guy, Can I use in Idea IDE but not the Eclipse

### ISSUE THREAD

**Issue by Bertkiing** [AndroidDeveloperLB/WebpifyYourAndroidApp#1]
No doubt that more and more people going to using the IDE of  IDEA by JetBrains. So I  want to use it in this but not the Eclipse.

**Comment by AndroidDeveloperLB** [comment]
I'm pretty sure the IDE of JetBrains is very capable of importing Eclipse projects.

**Comment by AndroidDeveloperLB** [comment]
Besides, this is a single time usage of it, just to compile it to an executable.

**Comment by Bertkiing** [comment]
I am so sorry for it.... Thanks for your reply.
